spring.application.name=spring-example

spring.ai.mcp.server.name=${spring.application.name}
spring.ai.mcp.server.version=0.0.1
spring.ai.mcp.server.stdio=true

spring.main.web-application-type=none
spring.main.banner-mode=off
logging.pattern.console=
