CREATE TABLE `AIGC_MODEL`
(
    `ID` VARCHAR(50) NOT NULL COMMENT '主鍵',
    `TYPE` VARCHAR(100) DEFAULT NULL COMMENT '類型: CHAT、EMBEDDING',
    `MODEL` VARCHAR(100) DEFAULT NULL COMMENT '模型名稱',
    `PROVIDER` VARCHAR(100) DEFAULT NULL COMMENT '供應商',
    `NAME` VARCHAR(100) DEFAULT NULL COMMENT '別名',
    `RESPONSE_LIMIT` INT DEFAULT NULL COMMENT '響應長度',
    `TEMPERATURE` DOUBLE DEFAULT NULL COMMENT '溫度',
    `TOP_P` DOUBLE DEFAULT NULL,
    `API_KEY` VARCHAR(100) DEFAULT NULL,
    `BASE_URL` VARCHAR(100) DEFAULT NULL,
    `SECRET_KEY` VARCHAR(100) DEFAULT NULL,
    `ENDPOINT` VARCHAR(100) DEFAULT NULL,
    `DIMENSION` INT DEFAULT NULL COMMENT '向量維數',
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='模型配置表';
